{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "learn-react.serviceAccountName" . }}
  labels:
{{ include "learn-react.labels" . | nindent 4 }}
{{- end -}}
